services:
  ## =============================================================================================
  ## MICROSSERVIÇOS
  ##==============================================================================================

  postgres:
    image: docker.io/library/postgres:latest
    container_name: ms-database
    ports:
      - "5433:5432" # O banco dos microsserviços estará acessível em localhost:5433.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: postgres
    networks:
      - my_network

  pessoa-app:
    # image: pessoa:latest
    build:
      context: ./pessoa
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      BOLETO_SERVICE_URL: https://boleto-app:8081
    networks:
      - my_network
    depends_on:
      - postgres

  boleto-app:
    # image: boleto:latest
    build:
      context: ./boleto # referência ao Dockerfile da aplicação boleto
    ports:
      - "8081:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - my_network
    depends_on:
      - postgres

  ## =============================================================================================
  ## KONG API GATEWAY
  ##==============================================================================================
  kong-database:
    image: docker.io/library/postgres:15
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my_network

  kong-migrations:
    image: docker.io/library/kong:latest
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_CASSANDRA_CONTACT_POINTS: "kong-database"
    command: "kong migrations bootstrap"
    restart: "on-failure"
    networks:
      - my_network

  kong:
    image: docker.io/library/kong:latest
    container_name: kong
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    restart: always
    networks:
      - my_network

  konga:
    image: pantsel/konga:latest
    container_name: konga
    depends_on:
      - kong
    ports:
      - "8082:1337"
    environment:
      NODE_ENV: "production"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
